const ConcertsActionTypes = {
    CREATE_CONCERT_START: 'CREATE_CONCERT_START',
    CREATE_CONCERT_SUCCESS: 'CREATE_CONCERT_SUCCESS',
    CREATE_CONCERT_FAILED: 'CREATE_CONCERT_FAILED',
};

export default ConcertsActionTypes;
