const ConcertsActionTypes = {
    CREATE_CONCERT_START: 'CREATE_CONCERT_START',
    CREATE_CONCERT_SUCCESS: 'CREATE_CONCERT_SUCCESS',
    CREATE_CONCERT_FAILED: 'CREATE_CONCERT_FAILED',
    GET_ALL_CONCERTS_FAILED: 'GET_ALL_CONCERTS_FAILED',
    GET_ALL_CONCERTS_SUCCESS: 'GET_ALL_CONCERTS_SUCCESS',
    GET_CONCERT_START: 'GET_CONCERT_START',
    GET_CONCERT_SUCCESS: 'GET_CONCERT_SUCCESS',
    GET_CONCERT_FAILED: 'GET_CONCERT_FAILED',
    UPDATE_FIELDS_FORM: 'UPDATE_FIELDS_FORM'
};

export default ConcertsActionTypes;
